 const constants = {
    LOADING_USER : "LOADING_USER",
    SUCCESS_USER : "SUCCESS_USER",
    FAILED_USER: "FAILED_USER",
    
    ADDING_USER: "ADDING_USER",
    USER_ADDED: "USER_ADDED" ,
    FAILED_TO_ADD: "FAILED_TO_ADD" ,
    
    REMOOVING_USER: "REMOOVING_USER" ,
    USER_REMOVED: "USER_REMOVED",
    FAILED_TO_REMOVE: "FAILED_TO_REMOVE",
   
    UPDATING_USER: "UPDATING_USER" ,
    USER_UPDATED: "USER_UPDATED",
    FAILED_TO_UPDATE: "FAILED_TO_UPDATE"
}


export default constants;
